import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import path from "path";
import Layout from "../../components/Layout";
import { postFilePaths, POSTS_PATH } from "../../utils/mdxUtils";

const Posts = ({ posts }) => {
    return (
        <Layout>
            <h1>Home Page</h1>
            <p>
                Click the link below to navigate to a page generated by{" "}
                <code>next-mdx-remote</code>.
            </p>

            {posts.map((post) => (
                <div key={post.filePath}>
                    <ul>
                        <li>
                            <Link
                                as={`/posts/${post.filePath.replace(
                                    /\.mdx?$/,
                                    ""
                                )}`}
                                href={`/posts/[slug]`}
                            >
                                <a>{post.data.title}</a>
                            </Link>
                        </li>
                        <p>{post.data.description}</p>
                    </ul>
                </div>
            ))}
        </Layout>
    );
};

export default Posts;

export function getStaticProps() {
    const posts = postFilePaths.map((filePath) => {
        const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
        const { content, data } = matter(source);

        return {
            content,
            data,
            filePath,
        };
    });

    return { props: { posts } };
}
